name: 'Sbt Dependency Updates Checker'
description: 'Adds a comment to a pull request with any dependency updates found'
inputs:
  token:
    description: 'Default GITHUB_TOKEN or a repository scoped personal access token.'
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - id: dependency-report
      run: sbt dependencyUpdatesReport
      shell: bash

    - id: pull-request
      run: |
        comments_url=$(jq --raw-output .pull_request.comments_url "$GITHUB_EVENT_PATH")
        # echo "::set-output name=comments_url::$(echo $comments_url)"
        echo "comments_url=$(echo $comments_url)" >> $GITHUB_OUTPUT
      shell: bash

    - id: check-if-should-comment
      run: |
        no_of_lines=$(wc -l target/dependency-updates.txt | awk '{print $1}')
        if [ $no_of_lines -gt 1 ]
        then
          # echo "::set-output name=post_comment::$(echo 1)"
          echo "post_comment=$(echo 1)" >> $GITHUB_OUTPUT
        else
          # echo "::set-output name=post_comment::$(echo 0)"
          echo "post_comment=$(echo 0)" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Add comment to PR
      if: ${{ steps.check-if-should-comment.outputs.post_comment == 1 }}
      run: |
        report="$(cat target/dependency-updates.txt)"
        report="${report//$'\n'/'\r\n'}"
        report="\`\`\`\r\n$report\r\n\`\`\`"

        JSON=$(cat <<EOF
        {
            "body": "$report"
        }
        EOF
        )

        curl \
        --request POST \
        --header "authorization: Bearer ${{ inputs.token }}" \
        --header "content-type: application/json" \
        --silent \
        "${{ steps.pull-request.outputs.comments_url }}" \
        --data "$JSON"
      shell: bash
branding:
  icon: 'check-square'
  color: 'red'